from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol

from app.schemas.client import Client
from app.schemas.data_source_field import DataSourceFieldUpsertRequest
from app.schemas.module import Module
from app.schemas.published_version import PublishedVersion
from app.schemas.screen import Screen
from app.schemas.tenant_catalog import DataSourceCreateRequest, TenantCatalog
from app.schemas.template_contract import (
    ScreenInstance,
    ScreenInstanceUpsertRequest,
    TenantTemplateBinding,
    TenantTemplateBindingUpsertRequest,
    VisualTemplate,
    VisualTemplateUpsertRequest,
)
from app.schemas.user import (
    CreateManagedUserRequest,
    ManagedUser,
    UpdateManagedUserRequest,
    ProfileUpdateRequest,
    User,
)
from app.schemas.client_visibility import ClientVisibilityResponse


@dataclass(frozen=True, slots=True)
class CredentialState:
    password_hash: str
    must_change_password: bool
    temporary_password_expires_at: datetime | None
    credentials_version: int


class ConfigRepositoryProtocol(Protocol):
    async def get_current_user(self, email: str | None = None, client_slug: str | None = None, user_id: str | None = None) -> User: ...
    async def update_current_user_profile(self, actor: User, payload: ProfileUpdateRequest) -> User: ...
    async def get_current_user_menu_order(self, actor: User) -> list[str]: ...
    async def update_current_user_menu_order(self, actor: User, item_ids: list[str]) -> list[str]: ...
    async def authenticate_user(self, email: str, password: str, client_slug: str | None = None) -> User | None: ...
    async def get_credential_state(self, user_id: str) -> CredentialState: ...
    async def change_password(self, user_id: str, expected_version: int, password_hash: str) -> int: ...
    async def list_managed_users(self, client_slug: str | None = None) -> list[ManagedUser]: ...
    async def create_managed_user(self, payload: CreateManagedUserRequest) -> ManagedUser: ...
    async def update_managed_user(self, user_id: str, payload: UpdateManagedUserRequest) -> ManagedUser: ...
    async def list_modules(self, client_id: str) -> list[Module]: ...
    async def get_screen(self, client_id: str, screen_id: str) -> Screen | None: ...
    async def get_client_by_slug(self, client_slug: str) -> Client | None: ...
    async def list_versions(self, client_slug: str) -> list[PublishedVersion]: ...
    async def get_version(self, client_slug: str, version: int) -> PublishedVersion | None: ...
    async def create_draft(self, client_slug: str, config: dict[str, Any]) -> PublishedVersion: ...
    async def mark_validated(self, client_slug: str, version: int, user_id: str, errors: list[str]) -> PublishedVersion: ...
    async def mark_validation_failed(self, client_slug: str, version: int, errors: list[str]) -> PublishedVersion: ...
    async def publish_version(self, client_slug: str, version: int, user_id: str) -> PublishedVersion: ...
    async def rollback_version(self, client_slug: str, version: int, user_id: str) -> PublishedVersion: ...
    async def archive_version(self, client_slug: str, version: int) -> PublishedVersion: ...
    async def get_validation_catalog(self, client_slug: str) -> dict[str, Any]: ...
    async def list_clients(self) -> list[Client]: ...
    async def get_client_visibility(self, client_slug: str) -> ClientVisibilityResponse: ...
    async def set_client_visibility(self, client_slug: str, target_type: str, target_id: str, visible: bool, actor_id: str | None = None) -> ClientVisibilityResponse: ...
    async def get_tenant_catalog(self, client_slug: str) -> TenantCatalog: ...
    async def upsert_data_source(self, client_slug: str, payload: DataSourceCreateRequest) -> TenantCatalog: ...
    async def upsert_data_source_field(self, client_slug: str, data_source_key: str, payload: DataSourceFieldUpsertRequest) -> TenantCatalog: ...
    async def list_visual_templates(self) -> list[VisualTemplate]: ...
    async def upsert_visual_template(self, payload: VisualTemplateUpsertRequest) -> VisualTemplate: ...
    async def list_template_bindings(self, client_slug: str) -> list[TenantTemplateBinding]: ...
    async def get_template_binding(self, client_slug: str, binding_id: str) -> TenantTemplateBinding | None: ...
    async def upsert_template_binding(self, client_slug: str, payload: TenantTemplateBindingUpsertRequest) -> TenantTemplateBinding: ...
    async def set_template_binding_validation(self, client_slug: str, binding_id: str, errors: list[str], user_id: str) -> TenantTemplateBinding: ...
    async def list_screen_instances(self, client_slug: str) -> list[ScreenInstance]: ...
    async def upsert_screen_instance(self, client_slug: str, payload: ScreenInstanceUpsertRequest) -> ScreenInstance: ...
